name: 02 AI Improve

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  improve:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Run improver
        run: python -m ai_loop.improver
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add README.md TRENDING.md logs/agents.log logs/update_log.txt logs/api_usage.json
            git commit -m "chore: apply AI improvements"
            git push
          fi
