name: Automated Codex Mixed Pipeline

on:
  schedule:
    - cron: '0 2 * * *'
    - cron: '0 3 * * 0'
  workflow_dispatch:
    inputs:
      mode:
        description: 'Run mode'
        required: false
        default: daily

jobs:
  daily:
    if: github.event.schedule == '0 2 * * *' || github.event.inputs.mode == 'daily'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai tiktoken pytest

      - name: Run daily Codex automation
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python trendspire_codex_mixed.py --mode daily

      - name: Upload Codex logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codex_logs_daily
          path: codex_logs/

  weekly:
    if: github.event.schedule == '0 3 * * 0' || github.event.inputs.mode == 'weekly'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai tiktoken pytest

      - name: Run weekly Codex automation
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python trendspire_codex_mixed.py --mode weekly

      - name: Upload Codex logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codex_logs_weekly
          path: codex_logs/
