name: Auto Codex Mixed

on:
  schedule:
    # Daily at 02:00 UTC
    - cron: '0 2 * * *'
    # Weekly every Sunday at 03:00 UTC
    - cron: '0 3 * * 0'
  workflow_dispatch:
    inputs:
      mode:
        description: "Select daily or weekly run"
        required: true
        default: daily
        type: choice
        options:
          - daily
          - weekly

concurrency:
  group: codex-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codex_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt gh

      # Daily trigger
      - name: Run Codex Bot (daily)
        if: |
          (github.event_name == 'schedule' && github.event.schedule == '0 2 * * *') ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.mode == 'daily')
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python trendspire_codex_mixed.py --mode daily

      # Weekly trigger
      - name: Run Codex Bot (weekly)
        if: |
          (github.event_name == 'schedule' && github.event.schedule == '0 3 * * 0') ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.mode == 'weekly')
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python trendspire_codex_mixed.py --mode weekly

      - name: Upload Codex Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codex-logs
          path: codex_logs/
