name: Integration Dry Run

on:
  workflow_dispatch:

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create test branch
        run: |
          git checkout -b integration-test-${{ github.run_id }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - name: Run automation scripts
        env:
          ENABLE_AI_README: 'true'
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python -m trendspire fetch
          python -m trendspire ai-readme --enable
      - name: Verify backups and logs
        run: |
          test -f TRENDING.md
          test -d backups
          test -f logs/update_log.txt
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add TRENDING.md README.md logs/ backups/
          git commit -m "Dry run update" || echo "Nothing to commit"
      - name: Push test branch
        run: git push origin HEAD
      - name: Open Test PR
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Integration Dry Run Test"
          branch: integration-test-${{ github.run_id }}
          body: |
            Automated dry run of the full pipeline.
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Close Test PR
        run: |
          gh pr close integration-test-${{ github.run_id }} --delete-branch --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
