name: Update Trending Digest

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Trending Digest
        run: python -m src.render_digest

      - name: Run tests
        run: pytest tests/test_trending.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add TRENDING.md
            git commit -m "chore: update TRENDING.md [skip ci]"
            git fetch origin main
            git rebase origin/main || git merge origin/main
            git push origin HEAD:main || git push --force-with-lease origin HEAD:main
          else
            echo "No changes to commit."
          fi
