name: Update Trending Digest

on:
  workflow_dispatch:  # Enables manual triggering
  schedule:            # Runs twice per day at 12-hour intervals (e.g., 00:00 and 12:00 UTC)
    - cron: '0 0 * * *'
    - cron: '0 12 * * *'
  push:
    paths:
      - 'src/**'
      - 'README.md'
      - 'TRENDING.md'
      - 'requirements.txt'
      - 'docs/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - run: python -m src.render_digest
      - name: Commit updated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add TRENDING.md README.md
          git commit -m "ci: update trending digest" || echo "Nothing to commit"
          git push
