name: Update Trending Digest

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - run: python -m src.render_digest
      - name: Commit updated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add TRENDING.md README.md
          git commit -m "ci: update trending digest"
          git push
